name: apps-desktop | helper

on:
  workflow_call:
    inputs:
      GIT_REPO:
        required: false
        type: string
      GIT_BRANCH:
        required: false
        type: string
      APP_ENV:
        required: true
        type: string
      RELEASE_CHANNEL:
        required: false
        type: string
        default: stable
      IS_DEBUG:
        required: false
        type: boolean
        default: false
      APP_NAME:
        type: string
      # wjdlz/NOTE: custom-fields

      CONFIG_APP:
        required: true
        type: string
      CONFIG_AUTHOR:
        required: true
        type: string
      CONFIG_ICON:
        required: true
        type: string
      APP_URL:
        required: true
        type: string
      APP_MENU:
        required: true
        type: string

env:
  V_APP_ENV: ${{ inputs.APP_ENV }}
  V_RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
  REPO: ${{ inputs.GIT_REPO || 'vezham/v0xFE-apps-desktop' }}
  BRANCH: ${{ inputs.GIT_BRANCH || 'timeline' }}
  CI_DIR: ./v/bin/ci
  ENTRY_POINT: ./
  # VX_APP_PATH:
  # VX_APP_NAME:

jobs:
  bnd:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]
        pnpm-version: [9.6.0]
        include:
          - os: ubuntu-latest
            artifact_name: ${{ inputs.APP_NAME }}-linux-artifacts
            # artifact_glob: 'make/**/*.{deb,rpm,AppImage}'
            artifact_glob: '*-linux-x64'
          - os: macos-latest
            artifact_name: ${{ inputs.APP_NAME }}-macos-artifacts
            # artifact_glob: 'make/**/*.dmg'
            # artifact_glob: 'make/zip/darwin/arm64/*.zip'
            artifact_glob: '*-darwin-arm64'
          - os: windows-latest
            artifact_name: ${{ inputs.APP_NAME }}-windows-artifacts
            # artifact_glob: 'make/**/*.exe'
            artifact_glob: '*-win32-x64'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Validate deployment settings
        uses: vezham/vx-deployer/.github/actions/deployment/validate@timeline
        with:
          APP_ENV: ${{ inputs.APP_ENV }}
          RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}

      - name: action | checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: vezham/vx-deployer/.github/actions/common/setup-checkout@timeline
        with:
          GIT_REPO: ${{ env.REPO }}
          GIT_BRANCH: ${{ env.BRANCH }}

      - name: action | gen $DX_APP_URL
        uses: vezham/vx-deployer/.github/actions/common/gen-dx-app-url@timeline

      - name: action | gen $ENV_VARS
        uses: vezham/vx-deployer/.github/actions/apps-desktop/setup-env@timeline

      - name: action | node & pnpm
        uses: vezham/vx-deployer/.github/actions/common/setup-install@timeline
        with:
          HEROUI_AUTH_TOKEN: ${{ secrets.HEROUI_AUTH_TOKEN }}

      - name: action | gen-build
        uses: vezham/vx-deployer/.github/actions/apps-desktop/gen-build@timeline

      - name: action | gen-artifact
        uses: vezham/vx-deployer/.github/actions/apps-desktop/gen-artifact@timeline
