name: chat_widget | helper

on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
    inputs:
      GIT_REPO:
        required: false
        type: string
      GIT_BRANCH:
        required: false
        type: string
      APP_ENV:
        required: true
        type: string
      RELEASE_CHANNEL:
        required: false
        type: string
        default: stable
      IS_DEBUG:
        required: false
        type: boolean
        default: false
      APP_NAME:
        type: string
      # wjdlz/NOTE: custom-fields

      APP_API_URL:
        required: true
        type: string
      WIDGET_URL:
        required: true
        type: string

env:
  REPO: ${{ inputs.GIT_REPO || 'vezham/v0xFE-apps-widgets' }}
  BRANCH: ${{ inputs.GIT_BRANCH || 'timeline' }}
  CI_DIR: ../../v/bin/ci
  ENTRY_POINT: ./apps_widgets/chat_widget
  VX_APP_PATH: apps_widgets/chat_widget
  VX_APP_NAME: chat_widget
  NX_APP_NAME: chat_widget

jobs:
  build_and_deploy:
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [9.6.0]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.ENTRY_POINT }}
    steps:
      - name: Validate deployment settings
        uses: vezham/vx-deployer/.github/actions/deployment/validate@timeline
        with:
          APP_ENV: ${{ inputs.APP_ENV }}
          RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}

      - name: checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}

      # wjdlz/TODO: ci-setup | fetch-credentials - via vezham CI host

      - name: ci-setup | extract $ENV_TOKENS
        id: extract-credentials
        shell: bash
        run: |
          # wjdlz/NOTE: save token to temporary file
          echo '${{ secrets.GCP_SA_KEY }}' > token.json

          # wjdlz/NOTE: extract & mask credentials
          ${{ env.CI_DIR }}/firebase/extract-credentials.sh token.json "$GITHUB_OUTPUT"

          # wjdlz/NOTE: clean up
          rm token.json

      - name: ci-setup | gen $ENV_TOKENS
        id: gen-env-tokens
        env:
          GCP_PROJECT_ID: ${{ steps.extract-credentials.outputs.GCP_PROJECT_ID }}
        run: |
          {
            echo "GCP_PROJECT_ID=$GCP_PROJECT_ID"
          } >> $GITHUB_ENV

      - name: ci-setup | short-sha
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: ci-setup | $SHA
        run: |
          echo 'SHA=${{ steps.short-sha.outputs.sha }}' >> $GITHUB_ENV

      - name: ci-setup | gen DX_APP_URL
        id: gen-dx-app-url
        # echo "DX_APP_URL=${{ env.VX_APP_NAME }}-${{ env.BRANCH }}-${{ env.SHA }}-${{ github.actor }}.ui.dx.tva.v0x.in" >> $GITHUB_ENV
        run: |
          echo "DX_APP_URL=${{ env.VX_APP_NAME }}-${{ env.BRANCH }}-${{ env.SHA }}" >> $GITHUB_ENV

      - name: setup | pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: setup | node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: setup | pnpm install
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: setup | .env vars
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: ${{ env.ENTRY_POINT }}
          envkey_V_APP_NAME: ${{ inputs.APP_NAME }}
          envkey_V_APP_ENV: ${{ inputs.APP_ENV }}
          envkey_V_RELEASE_CHANNEL: ${{ inputs.RELEASE_CHANNEL }}
          envkey_V_IS_DEBUG: ${{ inputs.IS_DEBUG }}
          envkey_V_APP_API_URL: ${{ inputs.APP_API_URL }}
          envkey_V_WIDGET_URL: ${{inputs.WIDGET_URL}}

      - name: setup | build
        run: npm run build --name=${{ env.NX_APP_NAME }}

      - name: logs | archive npm failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs

      - name: cloud-setup | firebase
        # shell: bash
        run: bash ${{ env.CI_DIR }}/firebase/main.sh ${{ env.VX_APP_PATH }}

      - name: cloud-cli | gcp/preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: gcp-preview
        with:
          expires: 30d
          channelId: ${{ env.DX_APP_URL }}
          repoToken: ${{ env.GITHUB_TOKEN }}
          projectId: ${{ env.GCP_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          # entryPoint: ${{ env.ENTRY_POINT }}

      - name: setup | fetch preview url
        uses: mad9000/actions-find-and-replace-string@5
        id: gcp-preview-url
        with:
          source: ${{ steps.gcp-preview.outputs.details_url }}
          find: '***'
          replace: ${{ env.GCP_PROJECT_ID }}

      - name: cloud-cli | gcp/live
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: gcp
        with:
          # expires: 30d
          channelId: live
          # repoToken: ${{ env.GITHUB_TOKEN }}
          projectId: ${{ env.GCP_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          # entryPoint: ${{ env.ENTRY_POINT }}

      # wjdlz/NOTE: cloud-setup | vercel - alternative

      - name: deployer | create commit comment
        uses: peter-evans/commit-comment@v1
        # - https://${{ env.DX_APP_URL }}
        with:
          body: |
            🚀 ${{ env.VX_APP_NAME }} Build deployed successfully to the following URLs
            - [Preview](${{ steps.gcp-preview-url.outputs.value }}) - ${{ steps.gcp-preview.outputs.expire_time }}
            - [Live Demo](https://${{ env.GCP_PROJECT_ID }}.web.app)
