name: playground-docs | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == '-timeline' || inputs.CALLER == 'next' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/playground-docs.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.PLAYGROUND_DOCS_TVA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      APP_NAME: playground-docs
      IS_DEBUG: true
      IS_BETA: true

  dev:
    name: dc/dev
    if: ${{ inputs.CALLER == 'deploy/dev' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/playground-docs.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.PLAYGROUND_DOCS_DEV_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/dev
      APP_NAME: playground-docs
      IS_DEBUG: true
      IS_BETA: true

  qa:
    name: dc/qa
    if: ${{ inputs.CALLER == 'deploy/qa' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/playground-docs.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.PLAYGROUND_DOCS_QA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/qa
      APP_NAME: playground-docs
      IS_BETA: true

  preview:
    name: dc/preview
    if: ${{ inputs.CALLER == 'deploy/preview' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/playground-docs.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.PLAYGROUND_DOCS_PREVIEW_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/preview
      APP_NAME: playground-docs

  live:
    name: dc/live
    if: ${{ inputs.CALLER == 'deploy/live' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/playground-docs.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.PLAYGROUND_DOCS_LIVE_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/live
      APP_NAME: playground-docs
