name: whats_new | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/whats_new.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.WHATS_NEW_TVA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: whats_new

  dev:
    name: dc/dev
    if: ${{ inputs.CALLER == 'deploy/dev' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/whats_new.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.WHATS_NEW_DEV_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/dev
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: whats_new

  qa:
    name: dc/qa
    if: ${{ inputs.CALLER == 'deploy/qa' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/whats_new.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.WHATS_NEW_QA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/qa
      IS_BETA: true
      APP_NAME: whats_new

  preview:
    name: dc/preview
    if: ${{ inputs.CALLER == 'deploy/preview' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/whats_new.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.WHATS_NEW_PREVIEW_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/preview
      APP_NAME: whats_new

  live:
    name: dc/live
    if: ${{ inputs.CALLER == 'deploy/live' || inputs.CALLER == '-scheduler' }}
    uses: vezham/vx-fe-deployer/.github/workflows/whats_new.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.WHATS_NEW_LIVE_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/live
      APP_NAME: whats_new
